# Generated by Django 3.0.6 on 2020-06-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customusermodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='phone',
        ),
    ]
