# Generated by Django 3.0.6 on 2020-06-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200601_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone',
            field=models.IntegerField(blank=True, help_text='(only number)', null=True),
        ),
    ]
